In [1]:
import pandas as pd

# Import classifier and create object
from ethnos_classifier import EthnosClassifier

clf = EthnosClassifier()

In [2]:
# Predict classes for "example.csv" table and save results to "example_pred.csv"
clf.predict('../data/example.csv', 'example_pred.csv')

/home/tarasov/ruEthnicNamesPublic/mlPipeline/ethnos_classifier.py:75: UserWarning: Warning: Some names in your data contain characters different from russian letters, "-" character or space. Results for this names will be "INVALID" or 0.0 for probabilities
  warnings.warn(

In [3]:
# Predict classes probabilities for "example.csv" table and save results to "example_pr_pred.csv"
clf.predict('../data/example.csv', 'example_pr_pred.csv', predict_probs=True)

/home/tarasov/ruEthnicNamesPublic/mlPipeline/ethnos_classifier.py:75: UserWarning: Warning: Some names in your data contain characters different from russian letters, "-" character or space. Results for this names will be "INVALID" or 0.0 for probabilities
  warnings.warn(

In [4]:
pd.read_csv('example_pred.csv')

     first_name    last_name       ethnos   agr_ethnos
0           Рая     Левтеева      Russian    BelRusUkr
1        Даниил     Леснухин      Russian    BelRusUkr
2      Айгулька  Гильмуллина        Tatar      BashTat
3       Евгения       Котова      Russian    BelRusUkr
4        Максим      Ефремов      Russian    BelRusUkr
...         ...          ...          ...          ...
1995  Маргарита      Петрова      Russian    BelRusUkr
1996    Дмитрий     Гречищев      Russian    BelRusUkr
1997     Андрий      Соколов    Ukrainian    BelRusUkr
1998     Эльшад        Алиев  Azerbaijani  Azerbaijani
1999  Анастасия    Лёвочкина   Belarusian    BelRusUkr

[2000 rows x 4 columns]

In [5]:
pd.read_csv('example_pr_pred.csv')

,first_name,last_name,Armenian_full,Azerbaijani_full,Bashkir_full,Belarusian_full,Buryat_full,Chechen_full,Dagestani_full,Georgian_full,...,CheDagIng_agr,Georgian_agr,Jewish_agr,KabAdKarBalOs_agr,Kalmyk_agr,KazKyr_agr,Moldovan_agr,TajUzb_agr,Tuvan_agr,Yakut_agr
0,Рая,Левтеева,0.0,0.000000,0.000000,0.130550,0.000000,0.111068,0.000000,0.0,...,0.176624,0.0,0.000000,0.048639,0.066826,0.0,0.000000,0.0,0.0,0.000000
1,Даниил,Леснухин,0.0,0.000000,0.007280,0.340103,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000
2,Айгулька,Гильмуллина,0.0,0.000000,0.389658,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000
3,Евгения,Котова,0.0,0.000000,0.000000,0.403698,0.007828,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000
4,Максим,Ефремов,0.0,0.000000,0.000000,0.114857,0.000000,0.000000,0.008672,0.0,...,0.000000,0.0,0.017015,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,Маргарита,Петрова,0.0,0.000000,0.000000,0.272126,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000
1996,Дмитрий,Гречищев,0.0,0.000000,0.000000,0.292515,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.012656
1997,Андрий,Соколов,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000
1998,Эльшад,Алиев,0.0,0.724431,0.000000,0.000000,0.000000,0.000000,0.275569,0.0,...,0.211232,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000
1999,Анастасия,Лёвочкина,0.0,0.000000,0.000000,0.572106,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.112912,0.0,0.0,0.000000